blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [path('', render_posts, name='posts'), path('<int:post_id>',post_detail, name='post_detail')
    
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from productos import views as productos_views
from django.conf.urls.static import static
from django.conf import settings 
from portfolio import views 
from productos import views as productos_views  # importar la vista


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),  
    path('blog/',include('blog.urls')), 
    path('productos/',include(('productos.urls','productos'), namespace='productos')),
    path('cart/checkout/', productos_views.cart_checkout, name='cart_checkout'),
    path('cart/confirm/', productos_views.cart_confirm, name='cart_confirm'),  # success return
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post       

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})  

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})
 
# blog/views.py
from django.shortcuts import render

def webpay_prueba(request):
    return render(request, "webpay_prueba.html")

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content%}

<div class="text-center">

    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

     <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"/>

    <div class="mb-4">
        <p>{{post.description|safe}}</p>
    </div>

</div>


  

{{post}}

{% endblock%}

blog/templates/posts.html
{% extends 'layout.html' %}


{% block content %}
<h1>Servicios</h1>

{% for post in posts %}

<div class="p-3">    
<div class="card-body bg-black">
    <div class="row">
         <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class=" img-fluid"/>
        </div>  
        
        <div class="col-9">
            <h2>{{post.title}}</h2>
            <p>{{post.description|striptags|truncatechars:100}}</p>   
            <p>{{post.date|date:'M D Y'|upper}}</p> 

            <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>     
        </div>
    </div>
</div>
</div>
{% endfor %}  {% endblock %}