blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [path('', render_posts, name='posts'), path('<int:post_id>',post_detail, name='post_detail')
    
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from productos import views as productos_views
from django.conf.urls.static import static
from django.conf import settings 
from portfolio import views 
from productos import views as productos_views  # importar la vista


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),  
    path('blog/',include('blog.urls')), 
    path('productos/',include(('productos.urls','productos'), namespace='productos')),
    path('cart/checkout/', productos_views.cart_checkout, name='cart_checkout'),
    path('cart/confirm/', productos_views.cart_confirm, name='cart_confirm'),  # success return
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path, include
from . import views

app_name = 'productos'
urlpatterns = [
    path('', views.producto, name='producto'),
]

urlpatterns = [
    path('', views.producto, name='producto'),  # Vista principal de productos
    path("webpay-prueba/", views.webpay_prueba, name="webpay_prueba"),
]

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Proyecto(models.Model):
    title = CharField(max_length=100)
    descrition = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)


    

portfolio/views.py
from django.shortcuts import render
from .models import Proyecto

from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import json
# 2.


def home(request):
    proyectos = Proyecto.objects.all() 
    return render(request, 'home.html', {'proyecto': proyectos})  

def webpay_prueba(request):
    return render(request, 'webpay_prueba.html')

# 2.
class CustomLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True

def cart_checkout(request):
    if request.method == "POST":
        data = json.loads(request.body)
        monto = data.get("total", 0)
        return render(request, "webpay_prueba.html", {"monto": monto})

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black ">
    <div class="col-md-4">
<img src="{% static 'portfolio/mi_foto01.jpg' %}" alt=""/>
    </div>

    <div class="col-md-8" my-auto>
        <h2>Hola, soy Pablo Mora</h2>
        <p>Analista Programado - FullStack</p>
        Me gusta crear aplicaciones web y móviles
        Mi stack de tecnologías incluye Django, React, React Native, Node.js y más.
        Estoy emocionado de compartir mis proyectos y conocimientos contigo.
        ¡Explora mi portafolio y no dudes en contactarme!</p>
        <p><p style="text-align: justify;">Soy estudiante de la carrera de <b>Analista Programador</b> del Instituto <b>Inacap</b>, 
      actualmente me encuentro cursando el 3er. semestre.</p> 
      <p style="text-align: justify;">Me desempeño como desarrollador web, con experiencia en proyectos tanto <B>front-end como back-end</B>. Mi pasión y mi objetivo es crear soluciones tecnológicas elegantes, eficientes y funcionales.</p>
<p style="text-align: justify;">Cuento con una marcada orientación al servicio, compromiso con el cumplimiento de los objetivos organizacionales y una atención
minuciosa a los detalles. Me destaco por mi capacidad de gestión, responsabilidad, liderazgo con humildad, y una excelente disposición
 para el trabajo en equipo, lo que me permite integrarme eficazmente en distintos entornos laborales y alcanzar metas comunes.</p>
<p style="text-align: justify;">Además, poseo una <B>trayectoria de más de 17 años en el ámbito de la informática</B>, desempeñándome en áreas como <B>soporte técnico, 
redes y desarrollo de software</B>, lo que me ha permitido adquirir una visión integral del rubro.</p>
<p style="text-align: justify;">Estoy muy entusiasmado con la posibilidad de colaborar juntos y aportar soluciones efectivas que impulsen el crecimiento de su negocio.</p></p>

<div class="col my-4 text-center">
<a href="https://www.linkedin.com/in/pablo-mora-gonz%C3%A1lez-957aa1188" class="btn btn-primary btn-lg rounde-0 my-3" target="_blank">LinkedIn</a>
    <a href="{% static 'portfolio/CV_PM_25.pdf' %}" class="btn btn-primary btn-lg rounde-0 my-3">Download CV</a>
</div>   
    </div>

</header>



<div class="row my-4 text-center">
    <h3>Mis Proyectos</h3>
  <div class="container text-center">
      <p class="lead text-muted mx-auto" style="text-align: justify; max-width: 700px;">
      Aquí presento una selección de proyectos que he desarrollado, 
      combinando creatividad, tecnología y enfoque en resultados.  
      Cada trabajo refleja mi compromiso con la calidad, la innovación y la mejora continua, 
      utilizando herramientas modernas y las mejores prácticas de desarrollo.  
      💡 Explora, revisa y conoce más sobre mi forma de crear soluciones digitales.
    </p>
  </div>
{% for proyecto in proyecto %}

<div class="col-md-4 p-4">
    <div class="card bg-black card-project">
         <img src="{{ proyecto.image.url }}" alt="{{proyecto.title}}" class="card-img-top"/>
        <div class="card-body">
     
                <h2>{{ proyecto.title }}</h2><p>{{ proyecto.description }}</p>
   

    {% if proyecto.url %}
     <a href="{{proyecto.url}}" class="btn btn-light rounded-0 btm-sm" target="_blank">{{proyecto.url}}</a> 

    {% endif %}
        </div>
    </div>
</div>
    {% endfor %} 
    
    {% endblock %}

</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<script src="{% static 'js/cart.js' %}"></script>
<body class="bg-dark text-light">

    <div id="cart-container" class="cart">
    <h5 class="cart-title">🛒 Carrito</h5>
    <ul id="cart-items"></ul>
    <p class="cart-total">
        <strong>Total:</strong> <span id="cart-total">$0</span>
    </p>
    <div class="cart-buttons">
        <button id="clear-cart" class="btn btn-danger btn-sm">🗑 Vaciar</button>
       <a href="{% url 'productos:webpay_prueba' %}" id="pay-cart" class="btn btn-success btn-sm">💳 Pagar</a>
    </div>
</div>


<style>
.cart {
    position: fixed;
    right: 20px;
    top: 100px;
    width: 250px;
    background: #222;
    color: white;
    padding: 10px;
    border-radius: 8px;
    z-index: 1000;
}
.cart ul {
    list-style: none;
    padding: 0;
    margin: 0;
}
.cart ul li {
    display: flex;
    justify-content: space-between;
    margin-bottom: 8px;
    font-size: 0.9rem;
}
</style>


    {% include 'partials/navbar.html' %}

    <div class="container p-4">

            {% block content %}
    {% endblock %}  
    </div>

    
</body>
</html>