blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [path('', render_posts, name='posts'), path('<int:post_id>',post_detail, name='post_detail')
    
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from productos import views as productos_views
from django.conf.urls.static import static
from django.conf import settings 
from portfolio import views 
from productos import views as productos_views  # importar la vista


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),  
    path('blog/',include('blog.urls')), 
    path('productos/',include(('productos.urls','productos'), namespace='productos')),
    path('cart/checkout/', productos_views.cart_checkout, name='cart_checkout'),
    path('cart/confirm/', productos_views.cart_confirm, name='cart_confirm'),  # success return
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path, include
from . import views

app_name = 'productos'
urlpatterns = [
    path('', views.producto, name='producto'),
]

urlpatterns = [
    path('', views.producto, name='producto'),  # Vista principal de productos
    path("webpay-prueba/", views.webpay_prueba, name="webpay_prueba"),
]

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Proyecto(models.Model):
    title = CharField(max_length=100)
    descrition = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)


    

portfolio/views.py
from django.shortcuts import render
from .models import Proyecto

from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import json
# 2.


def home(request):
    proyectos = Proyecto.objects.all() 
    return render(request, 'home.html', {'proyecto': proyectos})  

def webpay_prueba(request):
    return render(request, 'webpay_prueba.html')

# 2.
class CustomLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True

def cart_checkout(request):
    if request.method == "POST":
        data = json.loads(request.body)
        monto = data.get("total", 0)
        return render(request, "webpay_prueba.html", {"monto": monto})

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic "href="/">AROM SPA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-lg-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Servicios</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'productos:producto' %}">Productos</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/CV_PM_25.pdf' %}" target="_blank">Download CV</a>
        </li>
     </ul> 
    </div>
  </div>
</nav>